Update build-nightly.yml

diff --git a/.github/workflows/build-nightly.yml b/.github/workflows/build-nightly.yml
--- a/.github/workflows/build-nightly.yml
+++ b/.github/workflows/build-nightly.yml
@@ -141,8 +141,7 @@ jobs:
             
       - name: Set up MSVC
         if: ${{ matrix.target == 'msvc' }}
-        run: |
-          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+        uses: ilammy/msvc-dev-cmd@v1
        
       - name: Install extra tools (MSVC)
         if: ${{ matrix.target == 'msvc' }}
@@ -172,11 +171,19 @@ jobs:
         with:
           msystem: MINGW64
           update: false
-          install: git make p7zip autoconf libtool autoconf-archive base-devel zip unzip automake-wrapper automake && pacman -Sy && pacman -S --noconfirm automake
+          install: git make p7zip autoconf libtool autoconf-archive base-devel zip unzip automake-wrapper automake
           pacboy: >-
             toolchain:p ccache:p cmake:p ninja:p spirv-tools:p glslang:p libzip:p lz4:p
             qt6:p boost:p nlohmann_json:p openssl:p ffmpeg:p fmt:p mbedtls:p 
             opus:p qt5:p zlib:p zstd:p sdl3:p rapidjson:p python-pip:p
+            
+      - name: Fix automake and progtest.m4
+        if: ${{ matrix.target == 'msys2' }}
+        shell: msys2 {0}
+        run: |
+            pacman -Sy --noconfirm
+            pacman -S --noconfirm automake
+            ls /usr/share/aclocal/progtest.m4 || (echo "progtest.m4 still missing!" && exit 1)
           
       - name: Disable line ending translation
         run: git config --global core.autocrlf input
